### ISSUE TITLE
About papers

### ISSUE THREAD

**Issue by yXiangXiong** [infinite-tao/MA-MTLN#3]
Hi, buddy. Can you share your paper here. I can't see this paper, because i have no money to pay for IEEE TMI.

**Comment by infinite-tao** [comment]
Hi，buddy. I uploaded this paper to the repository .

**Comment by yXiangXiong** [comment]
> Hi，buddy. I uploaded this paper to the repository .

Thanks

**Comment by PussyCat0700** [comment]
> Hi，buddy. I uploaded this paper to the repository .

Thanks, it's of great help to me!
